language: node_js
node_js:
-10.9.0
cache: npm

before_install:
  - mkdir dist
  - ls
install:
  - npm install
  - ls -la

script:
  - npm test
  - npm start

deploy:
  provider: script
  skip-cleanup: true
  github-token: $GITHUB_TOKEN